/**
 * Pinewood Derby — Universal API Client
 * Auto-generated by setup.py. Do NOT edit manually — re-run setup.py.
 *
 * Provides: createClient(config) → { from, channel, storage, functions }
 * Works identically whether backend_mode is "supabase" or "local".
 */

// Placeholder — overwritten by setup.py
const CONFIG = {
  backend_mode:  "supabase",
  backend_url:   "",
  anon_key:      "",
  scoring_mode:  "heat",
  num_lanes:     4,
  track_name:    "Pinewood Derby",
  admin_pin:     "2468",
  settings_pin:  "1357",
  frontend_mode: "github_pages",
};
