#!/usr/bin/env python3
"""
Pinewood Derby OpenSource — Setup Wizard Launcher
Starts a local web server that serves the visual setup wizard,
then writes config.json and frontend/config.js when submitted.

Usage: python3 setup.py
"""
import json, os, sys, socket, webbrowser, threading
from pathlib import Path
from http.server import HTTPServer, BaseHTTPRequestHandler
from urllib.parse import parse_qs, urlparse

ROOT       = Path(__file__).parent
CONFIG_OUT = ROOT / "config.json"
WIZARD_DIR = ROOT / "wizard"

PORT = 8787  # separate from the main app port


def _get_local_ip() -> str:
    """Return the machine's LAN IP, or 'localhost' as fallback."""
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        return "localhost"


def write_config(data: dict):
    CONFIG_OUT.write_text(json.dumps(data, indent=2))
    print(f"\n✅  Config written to {CONFIG_OUT}")
    _write_frontend_config(data)
    print("\n🏁  Setup complete!")
    print(f"    Run the race server with:  python3 run.py\n")


def _write_frontend_config(cfg: dict):
    """Generate frontend/config.js from config.json."""
    frontend_cfg = ROOT / "frontend" / "config.js"
    frontend_cfg.parent.mkdir(parents=True, exist_ok=True)

    if cfg["backend_mode"] == "supabase":
        js = f"""// Auto-generated by setup.py — do not edit manually
// Re-run setup.py to change settings
const CONFIG = {{
  backend_mode:     "supabase",
  backend_url:      "{cfg.get('supabase_url', '')}",
  anon_key:         "{cfg.get('supabase_anon_key', '')}",
  scoring_mode:     "{cfg.get('scoring_mode', 'heat')}",
  num_lanes:        {cfg.get('num_lanes', 4)},
  track_name:       "{cfg.get('track_name', 'Pinewood Derby')}",
  admin_pin:        "{cfg.get('admin_pin', '2468')}",
  settings_pin:     "{cfg.get('settings_pin', '1357')}",
  frontend_mode:    "{cfg.get('frontend_mode', 'github_pages')}",
}};
"""
    else:
        host = cfg.get("local_host", "0.0.0.0")
        display_host = _get_local_ip() if host == "0.0.0.0" else host
        port = cfg.get("local_port", 8080)
        js = f"""// Auto-generated by setup.py — do not edit manually
// Re-run setup.py to change settings
const CONFIG = {{
  backend_mode:     "local",
  backend_url:      "http://{display_host}:{port}",
  anon_key:         "",
  scoring_mode:     "{cfg.get('scoring_mode', 'heat')}",
  num_lanes:        {cfg.get('num_lanes', 4)},
  track_name:       "{cfg.get('track_name', 'Pinewood Derby')}",
  admin_pin:        "{cfg.get('admin_pin', '2468')}",
  settings_pin:     "{cfg.get('settings_pin', '1357')}",
  frontend_mode:    "{cfg.get('frontend_mode', 'local')}",
}};
"""

    frontend_cfg.write_text(js)
    print(f"✅  Frontend config written to {frontend_cfg}")


class WizardHandler(BaseHTTPRequestHandler):
    _done = threading.Event()

    def log_message(self, *args):
        pass  # silent

    def do_GET(self):
        path = urlparse(self.path).path
        if path in ("/", "/setup"):
            self._serve_file(WIZARD_DIR / "index.html", "text/html; charset=utf-8")
        elif path.startswith("/wizard/"):
            fname = path.lstrip("/wizard/")
            self._serve_file(WIZARD_DIR / fname, "text/javascript")
        else:
            self.send_response(404); self.end_headers()

    def do_POST(self):
        if urlparse(self.path).path == "/api/setup":
            length = int(self.headers.get("Content-Length", 0))
            body   = self.rfile.read(length)
            data   = json.loads(body)
            write_config(data)

            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()
            self.wfile.write(b'{"ok": true}')

            # Stop the server after a short delay so response is sent
            threading.Timer(0.5, lambda: WizardHandler._done.set()).start()
        else:
            self.send_response(404); self.end_headers()

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def _serve_file(self, path: Path, mime: str):
        if not path.exists():
            self.send_response(404); self.end_headers()
            return
        data = path.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", mime)
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)


if __name__ == "__main__":
    existing = ""
    if CONFIG_OUT.exists():
        try:
            existing = CONFIG_OUT.read_text()
            print(f"⚠️   Existing config.json found. The wizard will pre-fill its values.")
        except Exception:
            pass

    url = f"http://localhost:{PORT}"
    print(f"\n🏎️   Pinewood Derby — Setup Wizard")
    print(f"    Opening {url} in your browser...")
    print(f"    (If it doesn't open, navigate there manually)\n")

    server = HTTPServer(("", PORT), WizardHandler)
    threading.Thread(target=lambda: webbrowser.open(url), daemon=True).start()

    try:
        while not WizardHandler._done.is_set():
            server.handle_request()
    except KeyboardInterrupt:
        print("\nSetup cancelled.")
        sys.exit(0)

    server.server_close()
